[package]
name = "BH-Diver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
quadrature = "0.1.2"
roots = "0.0.8"
